I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 51, in script
    user_nvl "I'm the other kid texting right now.."
NameError: Name 'username' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 51, in script
    user_nvl "I'm the other kid texting right now.."
  File "C:\Users\moyar\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\moyar\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\moyar\Downloads\renpy-8.2.0-sdk\renpy\exports.py", line 1493, in say
    who(what, *args, **kwargs)
  File "C:\Users\moyar\Downloads\renpy-8.2.0-sdk\renpy\character.py", line 1374, in __call__
    who = self.prefix_suffix("who", self.who_prefix, who, self.who_suffix)
  File "C:\Users\moyar\Downloads\renpy-8.2.0-sdk\renpy\character.py", line 1290, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "C:\Users\moyar\Downloads\renpy-8.2.0-sdk\renpy\character.py", line 1270, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\moyar\Downloads\renpy-8.2.0-sdk\renpy\substitutions.py", line 368, in substitute
    s = interpolate(s, kwargs) # type: ignore
  File "C:\Users\moyar\Downloads\renpy-8.2.0-sdk\renpy\substitutions.py", line 86, in interpolate
    raise e
  File "C:\Users\moyar\Downloads\renpy-8.2.0-sdk\renpy\substitutions.py", line 78, in interpolate
    value = renpy.python.py_eval(code, {}, scope)
  File "C:\Users\moyar\Downloads\renpy-8.2.0-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\moyar\Downloads\renpy-8.2.0-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
  File "C:\Users\moyar\Downloads\renpy-8.2.0-sdk\renpy\substitutions.py", line 310, in __getitem__
    raise NameError("Name '{}' is not defined.".format(key))
NameError: Name 'username' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.0.24012702
Discord In Your Heart 1.0
Sat Feb 17 11:59:11 2024
